name: odds_viewer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.4
  launch_review: ^3.0.0
  flutter_share_me: ^0.11.0
  social_share: ^2.1.1
  http: ^0.13.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  grouped_list: ^4.1.0
  material_segmented_control: ^3.1.2
  dotted_border: ^2.0.0+1
  web_socket_channel: ^2.1.0
  socket_io_client: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen: ^1.3.5
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/brand-new-logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Resources/privacy.html
    - assets/icons/new-logo.jpg
    - assets/icons/brand-new-logo.png
    - assets/icons/contact.png
    - assets/icons/contact_active.png
    - assets/icons/cricket.png
    - assets/icons/cricket_active.png
    - assets/icons/feedback.png
    - assets/icons/feedback_active.png
    - assets/icons/football.png
    - assets/icons/football_active.png
    - assets/icons/live1.png
    - assets/icons/live_active.png
    - assets/icons/news.png
    - assets/icons/news_active.png
    - assets/icons/point.png
    - assets/icons/point-active.png
    - assets/icons/settings.png
    - assets/icons/settings_active.png
    - assets/icons/upcoming.png
    - assets/icons/upcoming_active.png
    - assets/icons/trophy.png
    - assets/icons/trophy-active.png
    - assets/icons/app_store.png
    - assets/icons/play_store.png
    - assets/icons/facebook.png
    - assets/icons/twitter.png
    - assets/icons/whats_app.png
    - assets/icons/instagram.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
  # For details regarding fonts from package dependencies,